
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./frontend:/app  # Optional: for live development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./backend:/app  # Optional: for live development
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Use value from .env
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}  # Use value from .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver_opts:
      o: bind
      type: none 
      device: data/postgres_data

