
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/app 
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: app_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

