# Generated by Django 4.2 on 2024-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_user_friends_user_isingame_user_isonline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='game.user'),
        ),
    ]
