# Generated by Django 4.2 on 2025-01-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_two_factor_code_user_two_factor_code_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_code_expiry',
        ),
    ]
