
const dictionary = {
    en: {
    singlePlayer: "Single Player",
    multiPlayer: "Multi Player",
    isFourPlayer: "2 vs 2",
    start: "Start",
    restart: "Restart",
    settingsBtn: "Settings",
    offcanvasHeader: "Menu",
    statisticsBtn: "Statistics",
    tournamentBtn: "Tournament",
    historyBtn: "History",
    modalSettings: "Settings",
    ballHeader: "Ball",
    "speed-ball": "Speed",
    "acceleration-ball": "Acceleration",
    AI: "AI",
    "difficulty-ai": "Difficulty",
    language: "Language",
    "language-choice": "Choose Language",
    "validate-btn-Stgs": "Save changes",
    "input-Username": "Choose name for player",
    "input-Username-Finish": "All the players are named",
    "title-tournament": "Create Tournament",
    "input-username-btn": "Save",
    "start-tournament": "Start Tournament",
    loginModal: "Login",
    loginHeader: "Login",
    password: "Password",
    login: "Login",        
    "validate-btn-login": "Save Choices",
    "nbr-player-tournament": "Choose number of players",
    "defaultValue-nbrPlayer": "Default value is 4",
    "create-Tournament1": "Tournament",
    "2modal-BackBtn": "Back",
    "tournament-panel": "Tournament",
    "round-display": "Round",
    "order-playing": "Match Order",
    "winnerTournament": "The champion is ",
    "finishTournament" : "Finish",
    "registerHeader": "Register",
    "confpassword": "Confirm Password",
    "login-registe": "Username",
    "validate-btn-register": "Save Choices",
    "registerModalBtn": "Register",
    "textSize": "Size Text",
    "text-Size": "Choose Size",
    "sizes": "Small",
    "sizem": "Medium",
    "sizel": "Large",
    "sizexl": "Extra Large",
    "modalStatistics": "HISTORY",
    "modalStatistic": "HISTORY",
    "nbrPlayer-Btn" : "Next",
    "logoutModal" : "LOGOUT",
    "profileModalLabel" : "PROFIL",
    "emailR" : "E-Mail",
    "login-change" : "Save changes",
    "regist-changes" : "Save changes",
    "stat-mode": "Mode",
    "stat-vict": "Victory",
    "stat-def": "Defeat",
    "stat-total": "Total",
    "stat-single": "Single Player",
    "stat-multi": "Multi Player",
    "stat-2v2": "2 v 2",
    "stat-tourn": "Tournament",
    "hist-mode": "Game Mode",
    "hist-date": "Date",
    "registerModalLabel": "REGISTER",
    "start-login": "Login",
    "start-password": "Password",
    "start-confpw": "Confirm Password",
    "start-mail": "E-mail",
    "register-save-btn": "Enter",
    "exampleModalLabel": "LOGIN",
    "login-start": "Login",
    "pw-start": "Password",
    "reset-password-link": "Forgot your password?",
    "validate-btn-login": "Enter"
  
},
fr: {
    singlePlayer: "Joueur Unique",
    multiPlayer: "Multi Joueur",
    isFourPlayer: "2 contre 2",
    start: "Commencer",
    restart: "Recommencer",
    settingsBtn: "Paramètres",
    offcanvasHeader: "Menu",
    statisticsBtn: "Statistiques",
    tournamentBtn: "Tournoi",
    historyBtn: "Historique",
    modalSettings: "Paramètres",
    ballHeader: "Balle",
    "speed-ball": "Vitesse",
    "acceleration-ball": "Accélération",
    AI: "IA",
    "difficulty-ai": "Difficulté",
    language: "Langue",
    "language-choice": "Choix de la langue",
    "validate-btn-Stgs": "Enregistre les choix",
    "input-Username": "Choisit les noms pour les joueurs",
    "input-Username-Finish": "Tous les joueurs ont été nommés",
    "title-tournament": "Créer Un Tournoi",
    "input-username-btn": "Enregistrer le choix",
    "start-tournament": "Commencer le tournoi",
    loginModal: "Connecter",
    loginHeader: "Connecter",
    password: "Mot de passe",
    login: "Nom d'utilisateur",
    "validate-btn-login": "Enregistre les choix",
    "nbr-player-tournament": "Choisit combien de joueurs",
    "defaultValue-nbrPlayer": "Valeur par défaut est 4",
    "create-Tournament1": "Tournoi",
    "2modal-BackBtn" : "Retour",
    "tournament-panel": "Tournoi",
    "round-display": "Tour",
    "order-playing": "Ordre des matchs",
    "winnerTournament" : "Le champion est ",
    "finishTournament" : "Terminer",
    "registerHeader": "Inscription",
    "confpassword": "Confirmation",
    "login-registe" : "Nom d'utilisateur",
    "validate-btn-register" : "Enregistre les choix",
    "registerModalBtn" : "Inscription",
    "textSize": "Grosseur de text",
    "text-Size": "Choisit la grosseur",
    "sizes": "Petit",
    "sizem": "Moyen",
    "sizel": "Gros",
    "sizexl": "Très gros",
    "modalStatistics": "HISTOIRE",
    "modalStatistic": "HISTOIRE",
    "nbrPlayer-Btn" : "Suivant",
    "logoutModal" : "Déconnexion",
    "profileModalLabel" : "PROFILE",
    "emailR" : "E-Mail",
    "login-change" : "Enregistre les choix",
    "regist-changes" : "Enregistre les choix",
    "stat-mode": "Mode",
    "stat-vict": "Victoire",
    "stat-def": "Défaite",
    "stat-total": "Total",
    "stat-single": "Joueur solo",
    "stat-multi": "Joueur multi",
    "stat-2v2": "2 contre 2",
    "stat-tourn": "Tournoi",
    "hist-mode": "Mode de jeu",
    "hist-date": "Date",
    "registerModalLabel": "S'INSCRIRE",
    "start-login": "Nom d'utilisateur",
    "start-password": "Mot de passe",
    "start-confpw": "Confirmer le mot de passe",
    "start-mail": "E-mail",
    "register-save-btn": "Valider",
    "exampleModalLabel": "CONNEXION",
    "login-start": "Identifiant",
    "pw-start": "Mot de passe",
    "reset-password-link": "Mot de passe oublié ?",
    "validate-btn-login": "Se connecter"
},
jp: {
    singlePlayer: "シングルプレイヤー",
    multiPlayer: "マルチプレイヤー",
    isFourPlayer: "2対2",
    start: "スタート",
    restart: "リスタート",
    settingsBtn: "設定",
    offcanvasHeader: "メニュー",
    statisticsBtn: "統計",
    tournamentBtn: "トーナメント",
    historyBtn: "履歴",
    modalSettings: "設定",
    ballHeader: "ボール",
    "speed-ball": "速度",
    "acceleration-ball": "加速度",
    AI: "AI",
    "difficulty-ai": "難易度",
    language: "言語",
    "language-choice": "言語を選択",
    "stat-tourn": "トーナメント",
    loginModal: "ログイン",
    loginHeader: "ログイン",
    password: "パスワード",
    login: "ログイン",
    "validate-btn-login": "選択を保存",
    "nbr-player-tournament": "プレイヤー数を選択",
    "defaultValue-nbrPlayer": "デフォルト値は4です",
    "create-Tournament1": "トーナメント",
    "2modal-BackBtn": "戻る",
    "tournament-panel": "トーナメント",
    "round-display": "ラウンド",
    "order-playing": "試合順",
    "winnerTournament": "チャンピオンは ",
    "finishTournament" : "フィニッシュ",
    "registerHeader": "登録",
    "confpassword": "パスワード確認",
    "login-registe": "ユーザー名",
    "validate-btn-register": "選択を保存",
    "registerModalBtn": "登録",
    "textSize": "テキストサイズ",
    "text-Size": "サイズを選ぶ",
    "sizes": "小さい",
    "sizem": "普通",
    "sizel": "大きい",
    "sizexl": "とくだい",
    "modalStatistics": "歴史",
    "modalStatistic": "歴史",
    "nbrPlayer-Btn" : "次",
    "logoutModal" : "ログアウト",
    "profileModalLabel" : "プロフィール",
    "emailR" : "メール",
    "login-change" : "選択を保存",
    "regist-changes" : "選択を保存",
    "stat-mode": "モード",
    "stat-vict": "勝利",
    "stat-def": "敗北",
    "stat-total": "合計",
    "stat-single": "シングルプレイヤー",
    "stat-multi": "マルチプレイヤー",
    "stat-2v2": "2対2",
    "stat-tourn": "トーナメント",
    "hist-mode": "ゲームモード",
    "hist-date": "日付",
    "registerModalLabel": "登録",
    "start-login": "ログイン",
    "start-password": "パスワード",
    "start-confpw": "パスワード確認",
    "start-mail": "Eメール",
    "register-save-btn": "登録",
    "exampleModalLabel": "ログイン",
    "login-start": "ログイン",
    "pw-start": "パスワード",
    "reset-password-link": "パスワードを忘れましたか？",
    "validate-btn-login": "ログイン",
    "validate-btn-Stgs": "選択を保存",
}
};

function changeLanguageProcess(language) {
    const select = dictionary[language];

    Object.keys(select).forEach(id => {
        const element = document.getElementById(id);
        if (element) {
            element.textContent = select[id];
        }
    });
}

export function changeLanguage() {
    document.getElementById('validate-btn-Stgs').addEventListener('click', () => {
        if (document.getElementById('menu').style.display != 'none') {
            const iLanguage = document.getElementById('languageSelection').value
                switch (iLanguage) {
                    case "1":
                        changeLanguageProcess('en');
                        break;
                    case "2":
                        changeLanguageProcess('fr');
                        break;
                    case "3":
                        changeLanguageProcess('jp');
                        break;
                }
            } else {
                alert('Cannot change game settings during a game !');
                return;
            }
    });
}

